### ISSUE TITLE
explicar para que son los asteriscos en el readme

### ISSUE THREAD

**Issue by jmanuellh** [ProyectoMigala/Formulario#3]

**Comment by kevin4moe** [comment]
Los * en que parte? Debes agregar más contexto

**Comment by jmanuellh** [comment]
![imagen](https://github.com/ProyectoMigala/Formulario/assets/12085233/5515a3f7-240f-4663-a29e-100c5c925582)

**Comment by kevin4moe** [comment]
Son para indicar que anteriormente fueron obligatorias, mañana actualizo la descripción para que quede claro
